/**
 * Seed Data: Categories
 *
 * Complete jewelry product categories with subcategories.
 * displayOrder determines the order in navigation menus.
 */

export const categoriesSeedData = [
  {
    name: "Rings",
    slug: "rings",
    subcategories: [
      "Engagement Rings",
      "Wedding Bands",
      "Cocktail Rings",
      "Eternity Rings",
      "Solitaire Rings",
      "Statement Rings",
      "Stackable Rings",
      "Promise Rings",
      "Signet Rings",
      "Birthstone Rings",
    ],
    image: "",
    displayOrder: 1,
    isActive: true,
  },
  {
    name: "Necklaces",
    slug: "necklaces",
    subcategories: [
      "Pendant Necklaces",
      "Chain Necklaces",
      "Choker Necklaces",
      "Layered Necklaces",
      "Statement Necklaces",
      "Collar Necklaces",
      "Lariat Necklaces",
      "Pearl Necklaces",
    ],
    image: "",
    displayOrder: 2,
    isActive: true,
  },
  {
    name: "Earrings",
    slug: "earrings",
    subcategories: [
      "Stud Earrings",
      "Hoop Earrings",
      "Drop Earrings",
      "Dangle Earrings",
      "Chandelier Earrings",
      "Huggie Earrings",
      "Jhumka Earrings",
      "Ear Cuffs",
      "Clip-On Earrings",
    ],
    image: "",
    displayOrder: 3,
    isActive: true,
  },
  {
    name: "Bracelets",
    slug: "bracelets",
    subcategories: [
      "Chain Bracelets",
      "Cuff Bracelets",
      "Bangle Bracelets",
      "Charm Bracelets",
      "Tennis Bracelets",
      "Link Bracelets",
      "Beaded Bracelets",
      "Slider Bracelets",
    ],
    image: "",
    displayOrder: 4,
    isActive: true,
  },
  {
    name: "Bangles",
    slug: "bangles",
    subcategories: [
      "Gold Bangles",
      "Diamond Bangles",
      "Silver Bangles",
      "Kundan Bangles",
      "Stackable Bangles",
      "Kada/Kangan",
      "Platinum Bangles",
    ],
    image: "",
    displayOrder: 5,
    isActive: true,
  },
  {
    name: "Pendants",
    slug: "pendants",
    subcategories: [
      "Solitaire Pendants",
      "Heart Pendants",
      "Religious Pendants",
      "Initial/Name Pendants",
      "Gemstone Pendants",
      "Locket Pendants",
      "Drop Pendants",
    ],
    image: "",
    displayOrder: 6,
    isActive: true,
  },
  {
    name: "Chains",
    slug: "chains",
    subcategories: [
      "Cable Chains",
      "Box Chains",
      "Curb Chains",
      "Rope Chains",
      "Figaro Chains",
      "Snake Chains",
      "Wheat Chains",
      "Singapore Chains",
    ],
    image: "",
    displayOrder: 7,
    isActive: true,
  },
  {
    name: "Mangalsutra",
    slug: "mangalsutra",
    subcategories: [
      "Traditional Mangalsutra",
      "Modern Mangalsutra",
      "Diamond Mangalsutra",
      "Short Mangalsutra",
      "Long Mangalsutra",
      "Tanmaniya",
    ],
    image: "",
    displayOrder: 8,
    isActive: true,
  },
  {
    name: "Anklets",
    slug: "anklets",
    subcategories: [
      "Simple Anklets",
      "Charm Anklets",
      "Chain Anklets",
      "Beaded Anklets",
      "Gold Anklets",
      "Silver Anklets",
    ],
    image: "",
    displayOrder: 9,
    isActive: true,
  },
  {
    name: "Nose Pins",
    slug: "nose-pins",
    subcategories: [
      "Diamond Nose Pins",
      "Gold Nose Pins",
      "Stud Nose Pins",
      "Ring Nose Pins",
      "Nath (Bridal)",
    ],
    image: "",
    displayOrder: 10,
    isActive: true,
  },
  {
    name: "Toe Rings",
    slug: "toe-rings",
    subcategories: [
      "Silver Toe Rings",
      "Gold Toe Rings",
      "Adjustable Toe Rings",
      "Bridal Toe Rings",
    ],
    image: "",
    displayOrder: 11,
    isActive: true,
  },
  {
    name: "Brooches & Pins",
    slug: "brooches-pins",
    subcategories: [
      "Lapel Pins",
      "Saree Pins",
      "Decorative Brooches",
      "Floral Brooches",
    ],
    image: "",
    displayOrder: 12,
    isActive: true,
  },
  {
    name: "Jewelry Sets",
    slug: "jewelry-sets",
    subcategories: [
      "Bridal Sets",
      "Necklace Sets",
      "Earring & Pendant Sets",
      "Complete Sets",
      "Kundan Sets",
      "Meenakari Sets",
      "Temple Jewelry Sets",
    ],
    image: "",
    displayOrder: 13,
    isActive: true,
  },
  {
    name: "Men's Jewelry",
    slug: "mens-jewelry",
    subcategories: [
      "Men's Rings",
      "Men's Bracelets",
      "Men's Chains",
      "Men's Pendants",
      "Cufflinks",
      "Tie Pins",
      "Men's Kada",
    ],
    image: "",
    displayOrder: 14,
    isActive: true,
  },
  {
    name: "Kids' Jewelry",
    slug: "kids-jewelry",
    subcategories: [
      "Kids' Earrings",
      "Kids' Bangles",
      "Kids' Rings",
      "Kids' Chains",
      "Baby Anklets",
      "Nazariya",
    ],
    image: "",
    displayOrder: 15,
    isActive: true,
  },
  {
    name: "Coins & Bars",
    slug: "coins-bars",
    subcategories: [
      "Gold Coins",
      "Silver Coins",
      "Gold Bars",
      "Silver Bars",
      "Religious Coins",
    ],
    image: "",
    displayOrder: 16,
    isActive: true,
  },
  {
    name: "Watches",
    slug: "watches",
    subcategories: [
      "Gold Watches",
      "Diamond Watches",
      "Silver Watches",
      "Luxury Watches",
    ],
    image: "",
    displayOrder: 17,
    isActive: true,
  },
];
