/**
 * Seed Data: Gemstones
 *
 * Prices are approximate market rates in INR per carat.
 * Admin can update prices from the dashboard at any time.
 *
 * Types:
 *   precious     — Diamond, Ruby, Emerald, Sapphire
 *   semi-precious — Amethyst, Topaz, Garnet, Peridot, etc.
 *   organic       — Pearl, Coral, Amber
 */

export const gemstonesSeedData = [
  // ────────────── PRECIOUS ──────────────
  {
    name: "Diamond",
    type: "precious" as const,
    hardness: 10,
    variants: [
      {
        name: "Round Brilliant VVS1 D",
        cut: "Round Brilliant",
        clarity: "VVS1",
        color: "D",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 500000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Round Brilliant VS1 F",
        cut: "Round Brilliant",
        clarity: "VS1",
        color: "F",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 320000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Round Brilliant VS2 G",
        cut: "Round Brilliant",
        clarity: "VS2",
        color: "G",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 250000,
        certification: "IGI",
        isActive: true,
      },
      {
        name: "Princess Cut VS1 F",
        cut: "Princess",
        clarity: "VS1",
        color: "F",
        shape: "Square",
        origin: "Natural" as const,
        pricePerCarat: 280000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Oval VS2 G",
        cut: "Oval",
        clarity: "VS2",
        color: "G",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 260000,
        certification: "IGI",
        isActive: true,
      },
      {
        name: "Lab Diamond Round VS1 E",
        cut: "Round Brilliant",
        clarity: "VS1",
        color: "E",
        shape: "Round",
        origin: "Lab-Created" as const,
        pricePerCarat: 45000,
        certification: "IGI",
        isActive: true,
      },
      {
        name: "SI1 I Accent Diamond",
        cut: "Round Single",
        clarity: "SI1",
        color: "I",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 80000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Ruby",
    type: "precious" as const,
    hardness: 9,
    variants: [
      {
        name: "Burmese Ruby Natural",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Pigeon Blood Red",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 350000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Thai Ruby Natural",
        cut: "Oval",
        clarity: "Slightly Included",
        color: "Dark Red",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 80000,
        certification: "",
        isActive: true,
      },
      {
        name: "Lab Ruby Round",
        cut: "Round",
        clarity: "Flawless",
        color: "Red",
        shape: "Round",
        origin: "Lab-Created" as const,
        pricePerCarat: 5000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Emerald",
    type: "precious" as const,
    hardness: 7.5,
    variants: [
      {
        name: "Colombian Emerald Natural",
        cut: "Emerald Step",
        clarity: "Minor Inclusions",
        color: "Vivid Green",
        shape: "Rectangular",
        origin: "Natural" as const,
        pricePerCarat: 300000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Zambian Emerald Natural",
        cut: "Oval",
        clarity: "Moderate Inclusions",
        color: "Deep Green",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 120000,
        certification: "",
        isActive: true,
      },
      {
        name: "Lab Emerald Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Green",
        shape: "Oval",
        origin: "Lab-Created" as const,
        pricePerCarat: 6000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Sapphire",
    type: "precious" as const,
    hardness: 9,
    variants: [
      {
        name: "Blue Sapphire Natural",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Royal Blue",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 200000,
        certification: "GIA",
        isActive: true,
      },
      {
        name: "Pink Sapphire Natural",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Pink",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 100000,
        certification: "",
        isActive: true,
      },
      {
        name: "Yellow Sapphire (Pukhraj)",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Yellow",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 50000,
        certification: "",
        isActive: true,
      },
      {
        name: "White Sapphire Natural",
        cut: "Round",
        clarity: "Eye Clean",
        color: "White",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 40000,
        certification: "",
        isActive: true,
      },
    ],
  },

  // ────────────── SEMI-PRECIOUS ──────────────
  {
    name: "Amethyst",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Deep Purple Amethyst",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Deep Purple",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 800,
        certification: "",
        isActive: true,
      },
      {
        name: "Light Amethyst Round",
        cut: "Round",
        clarity: "Eye Clean",
        color: "Light Purple",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 400,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Topaz",
    type: "semi-precious" as const,
    hardness: 8,
    variants: [
      {
        name: "Swiss Blue Topaz",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Swiss Blue",
        shape: "Oval",
        origin: "Treated" as const,
        pricePerCarat: 600,
        certification: "",
        isActive: true,
      },
      {
        name: "London Blue Topaz",
        cut: "Emerald Step",
        clarity: "Eye Clean",
        color: "Deep Blue",
        shape: "Rectangular",
        origin: "Treated" as const,
        pricePerCarat: 900,
        certification: "",
        isActive: true,
      },
      {
        name: "Imperial Topaz",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Golden Orange",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 5000,
        certification: "",
        isActive: true,
      },
      {
        name: "White Topaz Round",
        cut: "Round",
        clarity: "Eye Clean",
        color: "White",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 200,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Garnet",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Red Garnet Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Deep Red",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 1500,
        certification: "",
        isActive: true,
      },
      {
        name: "Tsavorite Green Garnet",
        cut: "Round",
        clarity: "Eye Clean",
        color: "Vivid Green",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 25000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Tanzanite",
    type: "semi-precious" as const,
    hardness: 6.5,
    variants: [
      {
        name: "AAA Tanzanite Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Violet Blue",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 30000,
        certification: "",
        isActive: true,
      },
      {
        name: "AA Tanzanite Round",
        cut: "Round",
        clarity: "Slightly Included",
        color: "Blue Violet",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 15000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Opal",
    type: "semi-precious" as const,
    hardness: 6,
    variants: [
      {
        name: "Australian White Opal",
        cut: "Cabochon",
        clarity: "Translucent",
        color: "Play of Color",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 8000,
        certification: "",
        isActive: true,
      },
      {
        name: "Ethiopian Fire Opal",
        cut: "Cabochon",
        clarity: "Translucent",
        color: "Fire Orange",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 4000,
        certification: "",
        isActive: true,
      },
      {
        name: "Black Opal",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Dark Play of Color",
        shape: "Freeform",
        origin: "Natural" as const,
        pricePerCarat: 50000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Peridot",
    type: "semi-precious" as const,
    hardness: 6.5,
    variants: [
      {
        name: "Peridot Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Yellow Green",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 1200,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Citrine",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Golden Citrine Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Golden Yellow",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 600,
        certification: "",
        isActive: true,
      },
      {
        name: "Madeira Citrine",
        cut: "Emerald Step",
        clarity: "Eye Clean",
        color: "Deep Orange",
        shape: "Rectangular",
        origin: "Natural" as const,
        pricePerCarat: 1500,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Aquamarine",
    type: "semi-precious" as const,
    hardness: 7.5,
    variants: [
      {
        name: "Aquamarine Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Sky Blue",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 5000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Tourmaline",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Pink Tourmaline Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Pink",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 8000,
        certification: "",
        isActive: true,
      },
      {
        name: "Green Tourmaline Oval",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Green",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 6000,
        certification: "",
        isActive: true,
      },
      {
        name: "Paraiba Tourmaline",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Neon Blue-Green",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 200000,
        certification: "GIA",
        isActive: true,
      },
    ],
  },
  {
    name: "Onyx",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Black Onyx Cabochon",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Black",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 300,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Turquoise",
    type: "semi-precious" as const,
    hardness: 6,
    variants: [
      {
        name: "Persian Turquoise Cabochon",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Sky Blue",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 3000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Lapis Lazuli",
    type: "semi-precious" as const,
    hardness: 5.5,
    variants: [
      {
        name: "Afghan Lapis Lazuli",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Royal Blue",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 1500,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Moonstone",
    type: "semi-precious" as const,
    hardness: 6,
    variants: [
      {
        name: "Rainbow Moonstone Cabochon",
        cut: "Cabochon",
        clarity: "Translucent",
        color: "Blue Sheen",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 1200,
        certification: "",
        isActive: true,
      },
    ],
  },

  // ────────────── ORGANIC ──────────────
  {
    name: "Pearl",
    type: "organic" as const,
    hardness: 3.5,
    variants: [
      {
        name: "South Sea Pearl White",
        cut: "None",
        clarity: "High Luster",
        color: "White",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 15000,
        certification: "",
        isActive: true,
      },
      {
        name: "Akoya Pearl White",
        cut: "None",
        clarity: "High Luster",
        color: "White with Pink Overtone",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 8000,
        certification: "",
        isActive: true,
      },
      {
        name: "Freshwater Pearl",
        cut: "None",
        clarity: "Medium Luster",
        color: "White",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 2000,
        certification: "",
        isActive: true,
      },
      {
        name: "Tahitian Black Pearl",
        cut: "None",
        clarity: "High Luster",
        color: "Black with Green Overtone",
        shape: "Round",
        origin: "Natural" as const,
        pricePerCarat: 20000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Coral",
    type: "organic" as const,
    hardness: 3.5,
    variants: [
      {
        name: "Italian Red Coral (Moonga)",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Red",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 5000,
        certification: "",
        isActive: true,
      },
      {
        name: "Japanese Red Coral",
        cut: "Cabochon",
        clarity: "Opaque",
        color: "Deep Red",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 12000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    // Kundan stones — traditional Indian jewelry
    name: "Kundan",
    type: "semi-precious" as const,
    hardness: 5,
    variants: [
      {
        name: "Polki Uncut Diamond",
        cut: "Uncut",
        clarity: "Included",
        color: "Off White",
        shape: "Freeform",
        origin: "Natural" as const,
        pricePerCarat: 15000,
        certification: "",
        isActive: true,
      },
      {
        name: "Kundan Glass Stone",
        cut: "Flat",
        clarity: "Opaque",
        color: "Assorted",
        shape: "Assorted",
        origin: "Lab-Created" as const,
        pricePerCarat: 200,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Cat's Eye (Lehsunia)",
    type: "semi-precious" as const,
    hardness: 8.5,
    variants: [
      {
        name: "Chrysoberyl Cat's Eye",
        cut: "Cabochon",
        clarity: "Translucent",
        color: "Honey Yellow",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 20000,
        certification: "",
        isActive: true,
      },
    ],
  },
  {
    name: "Hessonite (Gomed)",
    type: "semi-precious" as const,
    hardness: 7,
    variants: [
      {
        name: "Ceylon Hessonite",
        cut: "Oval",
        clarity: "Eye Clean",
        color: "Honey-Cinnamon",
        shape: "Oval",
        origin: "Natural" as const,
        pricePerCarat: 3000,
        certification: "",
        isActive: true,
      },
    ],
  },
];
